### ISSUE TITLE
Docker network keeps getting deleted

### ISSUE THREAD

**Issue by bluecalx4** [duhio/docker-compose-usenet#3]
I've been using this stack on my new Unraid server and it's been running great. Thank you for the work. I do have one little issue still. Whenever I shut off all the containers off or reboot, it deletes the "dockercomposeusenet" network. I have to run the compose script again to get it back and the containers up and running again. Is this normal?

**Comment by stevewm** [comment]
Glad to hear that you found it useful! Just rebooted my server and it does indeed remove user-defined networks. That's not what I would expect, and I didn't see it because my server hadn't been rebooted, thanks for the bug report.

It's due to unRAID being in-memory and so changes end up being ephemeral unless there's built-in support for persisting them. UnRAID 6.4.1 added support for persisting user-defined Docker networks. You can find the setting in the Docker tab if you enable Advanced View. You'll need to stop the Docker service first to be able to change the setting. I've just given it a try and it does seem to solve the issue.

If you've not updated to 6.4.1 you can add the following `/boot/config/go`:
```
/usr/local/bin/docker-compose --project-directory /boot/docker-compose-usenet/ up -d
```

I'll update the README to point people towards the setting. Thanks for catching this one!
