### ISSUE TITLE
Ombi reverse proxy auth bypass

### ISSUE THREAD

**Issue by bluecalx4** [duhio/docker-compose-usenet#5]
Is there any way to have the reverse proxy auth bypassed just for Ombi?

**Comment by stevewm** [comment]
This isn't something I'd personally do, or recommend, given you can't guarantee that Ombi is secure. 

However, you can accomplish this by removing the authentication section from `traefik.toml` and labeling individual containers with the `traefik.frontend.auth.basic` label as per the [Traefik documentation](https://docs.traefik.io/configuration/backends/docker/#on-containers). 

Of course with this approach you will need to define the user:pass combos on _every_ service rather than simply once in `.htpasswd`.

**Comment by bluecalx4** [comment]
Thank you for the info. The reason I want to do this is so I can setup the internal Ombi auth system and make accounts for friends. I don't want to give out my reverse proxy username and password to friends.
